project_id = "192acf3b-1dc7-47f0-8210-aac289339f1c"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.contact-form]
verify_jwt = false

[functions.configurator-form]
verify_jwt = false
