export const glossaryTranslations = {
  EN: {
    badge: "Learn the Lingo",
    title: "Web Development",
    titleHighlight: "Glossary",
    subtitle: "A comprehensive dictionary of web development and digital marketing terms to help you understand the industry better.",
    searchPlaceholder: "Search terms...",
    noResults: "No terms found matching your search.",
    learnMore: "Learn More",
    loadMore: "Load More",
    showingOf: "Showing {shown} of {total} terms",
    allLetters: "All",
    categories: {
      All: "All",
      Development: "Development",
      Design: "Design",
      Marketing: "Marketing",
      Business: "Business",
      Security: "Security",
      General: "General",
    },
    // GlossaryTerm page
    glossary: "Glossary",
    definition: "Definition",
    backToGlossary: "Back to Glossary",
    whatIs: "What is",
    whyItMatters: "Why It Matters",
    realWorldExamples: "Real-World Examples",
    relatedTerms: "Related Terms",
    learnMoreResources: "Learn More",
    needHelp: "Need help with",
    teamCanHelp: "Our team can help you integrate this into your project.",
    getInTouch: "Get in Touch",
  },
  CZ: {
    badge: "Naučte se terminologii",
    title: "Slovník pojmů",
    titleHighlight: "webového vývoje",
    subtitle: "Kompletní slovník pojmů z oblasti webového vývoje a digitálního marketingu, který vám pomůže lépe porozumět oboru.",
    searchPlaceholder: "Hledat pojmy...",
    noResults: "Nebyly nalezeny žádné pojmy odpovídající vašemu hledání.",
    learnMore: "Zjistit více",
    loadMore: "Načíst další",
    showingOf: "Zobrazeno {shown} z {total} pojmů",
    allLetters: "Vše",
    categories: {
      All: "Vše",
      Development: "Vývoj",
      Design: "Design",
      Marketing: "Marketing",
      Business: "Byznys",
      Security: "Bezpečnost",
      General: "Obecné",
    },
    // GlossaryTerm page
    glossary: "Slovník",
    definition: "Definice",
    backToGlossary: "Zpět na slovník",
    whatIs: "Co je",
    whyItMatters: "Proč na tom záleží",
    realWorldExamples: "Příklady z praxe",
    relatedTerms: "Související pojmy",
    learnMoreResources: "Více informací",
    needHelp: "Potřebujete pomoc s",
    teamCanHelp: "Náš tým vám může pomoci implementovat toto do vašeho projektu.",
    getInTouch: "Kontaktujte nás",
  },
  SK: {
    badge: "Naučte sa terminológiu",
    title: "Slovník pojmov",
    titleHighlight: "webového vývoja",
    subtitle: "Kompletný slovník pojmov z oblasti webového vývoja a digitálneho marketingu, ktorý vám pomôže lepšie porozumieť odboru.",
    searchPlaceholder: "Hľadať pojmy...",
    noResults: "Neboli nájdené žiadne pojmy zodpovedajúce vášmu hľadaniu.",
    learnMore: "Zistiť viac",
    loadMore: "Načítať ďalšie",
    showingOf: "Zobrazených {shown} z {total} pojmov",
    allLetters: "Vše",
    categories: {
      All: "Všetko",
      Development: "Vývoj",
      Design: "Dizajn",
      Marketing: "Marketing",
      Business: "Biznis",
      Security: "Bezpečnosť",
      General: "Všeobecné",
    },
    // GlossaryTerm page
    glossary: "Slovník",
    definition: "Definícia",
    backToGlossary: "Späť na slovník",
    whatIs: "Čo je",
    whyItMatters: "Prečo na tom záleží",
    realWorldExamples: "Príklady z praxe",
    relatedTerms: "Súvisiace pojmy",
    learnMoreResources: "Viac informácií",
    needHelp: "Potrebujete pomoc s",
    teamCanHelp: "Náš tím vám môže pomôcť implementovať toto do vášho projektu.",
    getInTouch: "Kontaktujte nás",
  },
};
